### ISSUE TITLE
example flow is empty

### ISSUE THREAD

**Issue by Bodge-IT** [tehbilly/node-red-contrib-docker#2]
Would be useful to see this.

**Comment by segaura** [comment]
...or, at least, include the example flow in the TODO list :-)

**Comment by tehbilly** [comment]
Hrm, I'm not sure I understand how that happened. I'll see if I've still got this available still and update the flow.json to match the image.

**Comment by Bodge-IT** [comment]
Thanks @tehbilly

**Comment by tehbilly** [comment]
Well, looks like the one I have locally from the original project was also empty. Whoops. I'll work on setting up the flow seen in the image to update the example with.

**Comment by tehbilly** [comment]
I apologize for taking so long, this is not a project I look at often (sadly), but I've managed to recreate a similar-enough version of the flow to try things out. Hopefully this helps!
